version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm cache clean --force
      - run: sudo npm i -g mocha
      - run: alias mocha='./node_modules/.bin/_mocha'
      - run: npm cache clean --force
      - run: sudo npm install
      - run:
          command: npm start
          background: true
      - run: sleep 5
      - run: npm run test
